# docker-compose-mysql-minio.yaml
version: "3.7"

services:
  # MySQL for Hive Metastore
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # Use Docker named volume to avoid Windows permission issues
    volumes:
      - mysqldir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=dataeng
      - MYSQL_PASSWORD=dataengineering_user
      - MYSQL_ROOT_PASSWORD=dataengineering
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pdataengineering_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - lakehouse-net

  # MinIO - S3-compatible storage for Hive/Trino/Spark
  minio:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    container_name: minio
    command: ["server", "/opt/data", "--console-address", ":9001"]
    volumes:
      - ../data/minio/:/opt/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_admin
    healthcheck:
      test: ["CMD", "curl -f http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - lakehouse-net

volumes:
  mysqldir: { }
  minio-data: { }

networks:
  lakehouse-net:
    external: true